/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5abec588-134b-47fb-b2f9-f8d077f45a66",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_z8cCjMdsA",
    "aws_user_pools_web_client_id": "1uv167n6sk83jum76ll971s5q8",
    "oauth": {}
};


export default awsmobile;
